name: jobsque_amit_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dropdown_textfield: ^1.0.8
  flutter:
    sdk: flutter
  flutter_sms: ^2.3.3
  flutter_svg: ^2.0.7
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_indicator: ^2.0.2
  http: ^1.1.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.3+1
  mask_text_input_formatter: ^2.5.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pinput: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/finalregistertitle.png
